# Generated by Django 6.1.1 on 2026-09-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorbankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('GST_CERTIFICATE', 'GST Certificate'), ('PAN_CARD', 'PAN Card'), ('REGISTRATION_CERTIFICATE', 'Registration Certificate'), ('MSME_CERTIFICATE', 'MSME Certificate'), ('BANK_PROOF', 'Bank Proof'), ('AGREEMENT', 'Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vendor_documents/')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
        ),
    ]
