# Generated by Django 6.1.1 on 2026-09-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendordocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('delivery_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pricing_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('service_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='vendors.vendor')),
            ],
        ),
    ]
