# Generated by Django 6.1.1 on 2026-09-29 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('procurement', '0002_requisitionapproval'),
        ('products', '0002_product'),
        ('vendors', '0005_vendorperformancehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quotation_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='procurement.purchaserequisition')),
            ],
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_items', to='products.product')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='RFQVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('RESPONDED', 'Responded'), ('DECLINED', 'Declined')], default='INVITED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='rfq.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_invitations', to='vendors.vendor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rfq', 'vendor'), name='unique_rfq_vendor')],
            },
        ),
    ]
