# Generated by Django 6.1.1 on 2026-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
        ('rfq', '0001_initial'),
        ('vendors', '0005_vendorperformancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='delivery_time',
            field=models.PositiveIntegerField(help_text='Overall delivery time in days.'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('rfq', 'vendor'), name='unique_quotation_per_rfq_vendor'),
        ),
    ]
