# Generated by Django 6.1.1 on 2026-09-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_quotation_delivery_time_and_more'),
        ('rfq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_comparisons', to=settings.AUTH_USER_MODEL)),
                ('quotations', models.ManyToManyField(related_name='comparisons', to='quotations.quotation')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_comparisons', to='rfq.rfq')),
                ('selected_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_comparisons', to='quotations.quotation')),
            ],
        ),
    ]
